### PR TITLE
Fix missing deleted files in sub-directories

### LINKED ISSUE #345: Source filters don't show deleted files
From the git view we can see the file vat.rpgleinc has been deleted, but when trying various source filters, we can not see the file vat.rpgleinc being listed as deleted. We had this functionality working in v1

https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/69a3604a-c9cd-480b-8d37-c45d13b23fcf

### PR DESCRIPTION
**Pull request by SanjulaGanepola**
Fixes #345

@edmundreinhardt Your change in #327 was good, but only showed deleted files at the root of the project. This PR includes the logic you added but when also expanding directories. I also removed some duplicate code as the `DeletedFile` class can simply extend `SourceFile`.

### CODE REVIEW

File: src/views/projectExplorer/sourceDirectory.ts [hunk 1]
```diff
@@ -31,9 +32,10 @@ export default class SourceDirectory extends TreeItem implements ProjectExplorer
 
         for (const child of this.sourceInfo.children) {
             try {
-                const statResult = await workspace.fs.stat(child.localUri);
```
Comment (edmundreinhardt) [inline src/views/projectExplorer/sourceDirectory.ts:34]: THANK YOU for removing the heavy stat() call!

**Review by edmundreinhardt — APPROVED** [review]
thank you for the improvements
better command safety
